Extract unlock1p

diff --git a/bin/2u b/bin/2u
--- a/bin/2u
+++ b/bin/2u
@@ -6,6 +6,23 @@ readonly ANYCONNECT_PREFIX=/opt/cisco/anyconnect
 readonly ONELOGIN_ITEM_ID=ok36jmwmuzf6pjjxmzzr64lxby
 
 #-----------------------------------------------------------------------------
+#                            ** 1Passowrd Helpers **
+#-----------------------------------------------------------------------------
+
+unlock1p() {
+    if [ -e ~/.1password ]; then
+        source ~/.1password
+    fi
+    if ! op get item "$ONELOGIN_ITEM_ID" >/dev/null 2>&1; then
+        if ! op signin >~/.1password; then
+            printf '2u: unlock failed.\n' >&2
+            exit 1
+        fi
+        source ~/.1password
+    fi
+}
+
+#-----------------------------------------------------------------------------
 #                            ** OneLogin Helpers **
 #-----------------------------------------------------------------------------
 
@@ -31,10 +48,7 @@ cmd_vpn_usage() {
 }
 
 cmd_vpn_connect() {
-    if ! op get item "$ONELOGIN_ITEM_ID" >/dev/null 2>&1; then
-        printf 'vpn: cannot get OneLogin item, are you signed in?\n' >&2
-        return 1
-    fi
+    unlock1p
     (
         oneLoginUser
         oneLoginPassword
