Add git-browse-link

diff --git a/kakoune/kakrc b/kakoune/kakrc
--- a/kakoune/kakrc
+++ b/kakoune/kakrc
@@ -482,3 +482,24 @@ define-command \
         printf 'edit %%{%s}\n' "$target"
     }
 }
+
+# Git
+# ‾‾‾
+
+define-command \
+    -override \
+    -params 0 \
+    git-browse-link %{
+    evaluate-commands %sh{
+        link=$(git browse-link "$kak_buffile" "$kak_selection_desc" 2>&1)
+        if [ $? -ne 0 ]; then
+            printf "fail '"
+            printf "%s" "$link" |sed -e "s/'/''/g"
+            printf "'\\n"
+            exit
+        fi
+        printf "set-register '\"' '"
+        printf "%s" "$link" |sed -e "s/'/''/g"
+        printf "'\\n"
+    }
+}
